export const memberTexts = {
  brunobarth: {
    name: "Bruno Barth",
    year: "1951",
    beruf: "Dozent für „Deutsch als Fremdsprache“ i.R.",
    position: "Vorsitzender",
    committees: [
      "Mitglied im Stadtrat",
      "Haupt- und Finanzausschuss",
      "Ausschuss für Bildung",
      "Eurode-Verbandsversammlung",
    ],
    description: [
      '(Gründungs)Mitglied "Betreute Schulen Aachen-Land e.V."',
      'Träger von 9 "Offenen Ganztagsgrundschulen" (OGS) mit über 130 Mitarbeiter/innen',
      "Mitglied im „Naturschutzbeirat“ der StädteRegion Aachen",
      "Mitglied „Naturfreunde“-Ortsgruppe Herzogenrath-Merkstein",
      "Vorstandsmitglied AWO-Ortgruppe Herzogenrath-Mitte",
    ],
    hobbies: ["Laufen", "Schwimmen", "Fußball", "Lesen"],
    image: "/2_Bruno.png",
  },
  hartmutprast: {
    name: "Hartmut Prast",
    year: "1954",
    beruf: "Diplom- Ingenieur",
    position: "stellv. Fraktionsvorsitzender",
    committees: [
      "Klima und Umwelt",
      "Arbeit, Soziales und Quartiersentwicklung",
    ],
    description: [
      "Hartmut ist seit vielen Jahren aktiv im Umweltschutz...",
      "lorem ipsum",
      "lorem ipsum2",
    ],
    hobbies: ["Lesen", "Wandern"],
    image: "/Hartmut-1.png",
  },
  utekurig: {
    name: "Ute Kurig",
    year: "1961",
    beruf: "Dipl.- Ing. Architektur",
    position: "sachkundige Bürgerin",
    committees: ["Hochbau und Gebäudemanagement"],
    description: [
      "Schwerpunkt in der Kommunalpolitik: Umwelt- und Planung, Bau- und Verkehr",
      "Aktiv in folgenden Organisationen: NaturFreunde Merkstein",
    ],
    hobbies: [
      "Schwimmen",
      "Laufen",
      "Radfahren",
      "Imkern",
      "Spinnen und Weben",
      "Reisen",
    ],
    image: "/Ute-1.png",
  },
  ralfhardt: {
    name: "Ralf Hardt",
    year: "1969",
    beruf: "Systemadministrator (B.Sc. staatlich geprüfter Informatiker)",
    position: "sachkundiger Bürger",
    committees: ["Mobilität & Tiefbau"],
    description: [
      "Kommunalpolitisch: Mitglied im Ausschuß Mobilität & Tiefbau",
      "Arbeitskreis Feuerwehr Sicherheit & Bevölkerungsschutz",
      "Arbeitskreis SmartCity",
      "(Gründungs)Mitglied Metropolis e.V. Würselen",
      'Mitglied "Herzogenrather Turnverein e.V."',
    ],
    hobbies: [
      "Volleyball",
      "Pfarrkarneval St. Mariä Himmelfahrt H’rath(seit 25Jahren Organisator Ausschank)",
      "Hund",
    ],
    image: "/Ralf-1.png",
  },
  heinzbekeschus: {
    name: "Heinz Bekeschus",
    year: "1955",
    beruf: "Dipl.-Kaufmann, Fluglotse i.R. ",
    position: "Stellvertretender UBL-Vorsitzender (kommissarisch)",
    committees: ["Ausschuss für Stadtentwicklung und Planung"],
    description: [
      "Stellvertreter im „Ausschuss für Hochbau und Gebäudemanagement“",
      "Mitglied im Vorstand der „Alzheimer Gesellschaft StädteRegion Aachen e.V.“",
    ],
    hobbies: ["Reisen", "Radfahren", " Alpines Wandern "],
    image: "/Heinz-1.png",
  },
};
